---
title: "Отчёт по заданию 1"
author: "Dmitrii Zhakota"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
# library(readr)
library(readxl)

library(tidyverse)
```

```{r}

trauma <- read_excel("trauma.xlsx", col_types = c("skip", 
     "numeric", "text", "text", "numeric", 
     "text", "numeric", "numeric", "numeric", 
     "numeric", "numeric", "numeric", "numeric"))

trauma <- trauma %>%
    mutate(across(c(id, Sex, Death), ~ as.factor(.x)))

# read_file("TZ.txt")

trauma <- trauma %>% 
  mutate(Height = str_replace_all(Height, "\"", "")) 

trauma$Height <- as.numeric(trauma$Height)
  
trauma <- trauma %>% 
  mutate(Height = round(((Height*2.54)/100), digits = 2))

trauma <- trauma %>% 
  mutate(Weight = round(Weight/2.2, digits = 1))




```

#1
```{r}
# Дайте описательную статистику для переменных, включённых в датасет.
trauma %>% 
  summary()

#Заменяем 0 на NA
trauma <- trauma %>%
    mutate(Hb = na_if(Hb, 0))

#Дополнительно  рассчитайте, у какого количества пациентов и в каком проценте случаев у пациентов был снижен уровень гемоглобина? Используйте следующие референтные значения (Мужчины:  13.5–16 г/дл, Женщины: 12–14 г/дл).

trauma <- trauma %>% 
  mutate(Hb_low = case_when((Sex == "Male" & Hb < 13.5) | (Sex == "Female" & Hb < 12) ~ 1, TRUE ~ 0))

Hb_low <- trauma %>% 
  group_by(Hb_low) %>%
  summarise(n = n()) %>%
  mutate(Percent = n/sum(n)*100) %>% round(2)

Hb_low <- Hb_low %>%
  mutate(Hb_low = recode(Hb_low, `0` = "Normal", `1` = "Low level"))


print(paste0(" Значение гемоглобны (Hb) снижено у: ", Hb_low$n[2], " обследованных "))
print(paste0(" Что составило: ", Hb_low$Percent[2], " % от общего количества обследованных (n = ", trauma %>% summarise(n()), ")"))
```

#2

```{r}
# Рассчитайте индекс массы тела у пациентов (кг / м2).  

trauma <- trauma %>% 
  mutate(BMI = (Weight/Height^2) %>% round(1))

# Каков был средний (M (SD)) уровень  ИМТ у пациентов, включённых в исследование?
BMI <- trauma %>% 
  summarise(Mean = mean(BMI), SD = sd(BMI)) %>% 
  round(2)

print(paste0(" Средний уровень ИМТ (M(SD)), у влючённых в исследование составил: ", BMI$Mean, "(", BMI$SD, ")"))

# Какая доля пациентов имела ожирение (ИМТ  > 30)? 
Obesity <- trauma %>% 
  mutate(Obesity = case_when(BMI > 30 ~ 1, TRUE ~ 0)) %>% 
  group_by(Obesity) %>% 
  summarise(n = n()) %>% 
  mutate(Percent = n/sum(n)*100) %>% 
  round(2)

Obesity <- Obesity %>%
  mutate(Obesity = recode(Obesity, `0` = "Normal", `1` = "Obesity"))

print(paste0(" Доля поциентов с ожирением (ИМТ>30) составила ", Obesity$Percent[2], " % от общего количества обследованных (n = ", trauma %>% summarise(n()), ")" ))
```

#3

```{r, }
# Как выглядит ROC-кривая для предсказания летального исхода в течение 24 часов по  переменной, характеризующей уровень гемоглобина? Постройте график. Чем может быть  обусловлена такая форма кривой?

library(pROC)

#Convert column Death to numeric
# trauma <- trauma %>%
#     mutate(across(c(id, Sex, Death), ~ as.numeric(.x)))


roc_curve_1 <- roc(Death ~ Hb, 
                   data = trauma,
                   ci = T) 

roc_curve_1 %>% 
    ggroc() + 
    geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "red") + 
    coord_equal() +
    theme_bw() 

# Отдельные графики по полу
trauma_male <- trauma %>% 
  dplyr::filter(Sex == "Male") 

roc_curve_m <- roc(Death ~ Hb, 
                   data = trauma_male,
                   ci = T) 

roc_curve_m %>% 
    ggroc() + 
    geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "red") + 
    coord_equal() +
    theme_bw()   

trauma_female <- trauma %>% 
  dplyr::filter(Sex == "Famale") 

roc_curve_f <- roc(Death ~ Hb, 
                   data = trauma_male,
                   ci = T) 

roc_curve_f %>% 
    ggroc() + 
    geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "red") + 
    coord_equal() +
    theme_bw()   

#########################Altenative plot with CI######################################
###https://programmersought.com/article/10166297014/##################################
rocobj <- plot.roc(trauma$Death, trauma$Hb,
                   
                   main="Confidence intervals", percent=FALSE,
                   
                   ci=TRUE, # compute AUC (of AUC by default)
                   
                   print.auc=TRUE) # print the AUC (will contain the CI)

ciobj <- ci.se(rocobj, # CI of sensitivity
               
               # specificities=seq(0, 100, 5)) # over a select set of specificities
               specificities=seq(0, 1, 0.01)) # over a select set of specificities

plot(ciobj, type="shape", col="#1c61b6AA") # plot as a blue shape
plot(ci(rocobj, of="thresholds", thresholds="best")) # add one threshol




print(paste0("Сделал графики отдельно для полов для демонстрации бимодальности общего"))
```

#4

```{r}
# Чему равна площадь под ROC-кривой, которую вы построили в вопросе 3? 
print(paste0(" Площадь под ROC-кривой составила: ", round(roc_curve_1$auc, digits = 2)))
  
# Чему равен 95%  двусторонний ДИ для площади под ROC-кривой, которую вы построили в вопросе 3? 
print(paste0(" 95% двусторонний ДИ для площади под ROC-кривой составил: ", round(roc_curve_1$ci[1], digits = 2), " - ", round(roc_curve_1$ci[3], digits = 2)))

```

#5

```{r, fig.width=3, fig.height=3, dpi=300}
# Проведите ROC-анализ и определите, какое пороговое значение является оптимальным для  предсказания летального исхода в течение 24 часов по шкале комы Глазго. 
# Какой  чувствительностью и специфичностью обладает данный порог?

roc_curve_2 <- roc(Death ~ GSC, 
                   data = trauma,
                   ci = T)
# roc_curve_2

roc_curve_2 %>% 
    ggroc() + 
    theme_bw() +
    geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "red") + 
    coord_equal()

roc_Glasgo <- roc_curve_2 %>% coords(x = "best", best.method = "closest.topleft")
roc_Glasgo <- roc_Glasgo %>% 
    mutate(sensitivity = round(sensitivity, digits = 2),
           specificity = round(specificity, digits = 2))

print( paste("Оптимальное пороговое значение: ", roc_Glasgo$threshold)) 
print( paste("Чувствительность для данного порогового значения: ", roc_Glasgo$sensitivity))
print( paste("Специфичность для данного порогового значения: ", roc_Glasgo$specificity))



```

#6
```{r}
# Какая из количественных переменных в датасете (включая рассчитанный вами ранее ИМТ) обладает наибольшей площадью под ROC-кривой? 
trauma %>% select(is.numeric) %>% names()

trauma %>% 
    select("Death",
           "Age",
           "Height",
           "Weight",
           "SBP",
           "DBP",
           "FOUR",
           "GSC",
           "Hb",
           "Hb_low",
           "BMI") %>%
    pivot_longer(cols = !Death) %>% 
    
    group_by(name) %>% 
    
    summarise(AUC = roc(Death, value, ci = T)$ci[2] %>% round(3),
              AUC_LCL = roc(Death, value, ci = T)$ci[1] %>% round(3),
              AUC_UCL = roc(Death, value, ci = T)$ci[3] %>% round(3)) %>% 
    dplyr::arrange(AUC) -> AUC_table

AUC_table

print(paste("Наибольшую площадь под кривой имеет признак FOUR:", AUC_table$AUC[10]))
# Как вы можете интерпретировать это знание? 
print(paste("Признак FOUR является наиболее значимым для предсказания летального исхода в течение 24 часов."))

# Какая количественная переменная имеет наименьшую площадь? 
print(paste("Наименьшую площадь под кривой имеет признак Height:", AUC_table$AUC[1]))


```




```{r eval=FALSE, include=FALSE}
roc_curve_Age <- roc(Death ~ Age, 
                   data = trauma,
                   ci = T) 

roc_curve_Height <- roc(Death ~ Height, 
                   data = trauma,
                   ci = T) 

roc_curve_Weight <- roc(Death ~ Weight,
                   data = trauma,
                   ci = T)

roc_curve_SBP <- roc(Death ~ SBP,
                   data = trauma,
                   ci = T)

roc_curve_DBP <- roc(Death ~ DBP,
                   data = trauma,
                   ci = T)

roc_curve_FOUR <- roc(Death ~ FOUR,
                   data = trauma,
                   ci = T)

roc_curve_GSC <- roc(Death ~ GSC,
                   data = trauma,
                   ci = T)

roc_curve_Hb <- roc(Death ~ Hb,
                   data = trauma,
                   ci = T)

roc_curve_Hb_low <- roc(Death ~ Hb_low,
                   data = trauma,
                   ci = T)

roc_curve_BMI <- roc(Death ~ BMI,
                   data = trauma,
                   ci = T)


print(paste0(" Площадь под ROC-кривой для Age составила: ", round(roc_curve_Age$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для Height составила: ", round(roc_curve_Height$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для Weight составила: ", round(roc_curve_Weight$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для SBP составила: ", round(roc_curve_SBP$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для DBP составила: ", round(roc_curve_DBP$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для FOUR составила: ", round(roc_curve_FOUR$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для GSC составила: ", round(roc_curve_GSC$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для Hb составила: ", round(roc_curve_Hb$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для Hb_low составила: ", round(roc_curve_Hb_low$auc, digits = 2)))
print(paste0(" Площадь под ROC-кривой для BMI составила: ", round(roc_curve_BMI$auc, digits = 2)))


print(paste("Наибольшую площадь под кривой имеет признак FOUR:", round(roc_curve_FOUR$auc, digits = 2)))
# Как вы можете интерпретировать это знание? 
print(paste("Признак FOUR является наиболее значимым для предсказания летального исхода в течение 24 часов."))

# Какая количественная переменная имеет наименьшую площадь? 
print(paste("Наименьшую площадь под кривой имеет признак BMI:", round(roc_curve_BMI$auc, digits = 2)))

```




