---
title: "StartLesson"
author: "Dmitrii"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)

```

```{r}
df <- read_tsv("data_tsv.tsv")
# df <- read.delim("GitHub/data_tsv.tsv")

# df <- read.csv("data/interim/df.csv")

df <- read_tsv("https://stepik.org/media/attachments/course/122402/data_tsv.tsv")


# write_tsv(df, "GitHub/df_tsv.tsv")
# write_rds(df, "data/raw/df.rds")

write.csv(df, "df.csv")

```

#5.1 Базовая статистика
```{r}
rm(list=ls())

mean(c(76, 65, 71, 16, 60, 29, 71, 46, 45, 41), na.rm = TRUE)

median(c(-15, 71, 77, 36, 66, -21, -48, -8))

min(c(48.11, 45.3, 58.42, 51.64, 62.07, 57.26, 49.69, 93.29, 81.18, 44.78, 55.1, 76.74, 58.08))


quantile(c(32.05, 93.85, 85.52, 56.69, 23.69, 11.29, 51.44, 63.09, 65.65, 35.73, 60.15, 30.93, -4.2))

var(c(76.22, 65, 19.69, 29.84, 37.18, 70.93, 64.78, 61.66, 49.03, 51.56))

IQR(c(63.92, 35.85, 26.9, 48.92, 43.1, 66.94, 47.06, 56.54, 29.1, 58.88))


x <- c(76.22, 65, 19.69, 29.84, 37.18, 70.93, 64.78, 61.66, 49.03, 51.56)
sd(x)/sqrt(sum(!is.na(x)))

```

#5.2
```{r}
rm(list=ls())

library(psych)
data <- read_rds("numeric_data.rds")

round(describe(data), digits = 2)

x <- read_rds("https://stepik.org/media/attachments/lesson/790859/factor_data.rds")

tab <- table(x$Группа, x$`Группа крови`)

prop.table(tab)

detach(package:psych)

```

#6.1
```{r}
library(tibble)

tibble(`var 1` = 1:10, `var 2` = `var 1` * 100)

detach(package:tibble)
```

#6.2
<!-- dplyr::left_join(), dplyr::right_join(), dplyr::inner_join(), dplyr::full_join() -->

<!-- Есть четыре функции, которые позволяют склеивать датафреймы по ключевым переменным (только два, назовём их x и y): -->

<!-- left_join(x, y): включает все строки, которые есть в x, отбрасывая из y те, которых нет; -->
<!-- right_join(x, y): включает все строки, которые есть в y, отбрасывая те, которых там нет; -->
<!-- inner_join(x, y): включает все строки, которые есть и в x и y; -->
<!-- full_join(x, y): просто включает все строки, которые есть хотя бы в x или y. -->
<!-- Каждый датафрейм должен иметь одну (или более) важных переменных: ключевых переменных. -->

<!-- Этот концепт очень прост. Должна быть уникальная переменная, например, ID пациента, по которой функция понимает, какую строку с какой сопоставлять. Это может быть не только одна переменная, но и их уникальное сочетание, например, ID пациента, его визиты, а также получаемый препарат. Эти три переменных и являются в таком случае уникальным ключом к сопоставлению строк. -->
```{r}

data_1 <- tibble(var_1 = 1:8) %>% mutate(id = row_number())

data_2 <- tibble(var_2 = rnorm(10)) %>% mutate(`Subject ID` = row_number())

data_1 %>% 
  left_join(data_2, by = c("id" = "Subject ID"))

data_1 %>% 
  right_join(data_2, by = c("id" = "Subject ID"))

data_1 %>% 
  inner_join(data_2, by = c("id" = "Subject ID"))

data_1 %>% 
  full_join(data_2, by = c("id" = "Subject ID"))
```

#6.4
```{r}
rm(list=ls())

data <- read_tsv("data_tsv.tsv")
str(data)

data %>%
  select(`Группа крови`, `Рост`)

# data %>% 
#   select(`Группа`, where(is.numeric) & function(x) mean(x, na.rm = TRUE) > 10)


data %>% select(`Пол`, `Группа`, `Базофилы_E1`)
data %>% select(`Группа`, (function(x) is.factor(x)) | where(function(x) is.numeric(x)))
data %>% select(`Группа`, function(x) !is.factor(x))
data %>% select(`Группа крови`, `Возраст`, function(x) anyNA(x))

#data %>% select(where(is.numeric) & where(function(x) sd(x, na.rm = TRUE) > 1))
# data %>% select(function(x) sd(x, na.rm = TRUE) > 1)
# data %>% select(function(x) any(str_detect(x, "Жен")))

data %>% select(contains("_E1"))

data %>% select(matches("_E\\d{1}"))

data %>% select(starts_with("Б"))

data %>% select(ends_with("E2"))

variables <- c("Пол", "Базофилы_E1", "Эритроциты_E2")
data %>% select(variables)
data %>% select(all_of(variables))

# Иерархия операторов
# 
# Приоритет логических операторов от высшего к низшему. 
# 
# x < y, x > y, x <= y, x => y, x == y, x != y (операторы сравнения)
# !x (логическое НЕ)
# x & y (логическое И)
# x | y (логическое ИЛИ)

data %>% 
  select(where(is.numeric)) %>% 
  select(where(function(x) sd(x, na.rm = TRUE) > 2 & mean(x, na.rm = TRUE) <10))

data %>% 
  select(where(is.numeric)) %>% 
  select(where(function(x) sd(x, na.rm = TRUE) > 2 | mean(x, na.rm = TRUE) <10 | median(x, na.rm = TRUE) >5))

data %>% 
  select(!where(is.numeric))

data %>% 
  select(`Пол`, `Эритроциты_E1`, everything())

data %>% 
  select(gender = `Пол`, `Эритроциты_Визит1` = `Эритроциты_E1`)


```

#6.5
```{r}
data %>% 
  slice(1:10)

data %>% 
  slice_head(prop=0.1)

data %>% 
  slice_tail(prop=0.1)

data %>% 
  slice_sample(prop=0.15)

data %>% 
  slice_min(`Возраст`)

# Для того, чтобы, фильтруя по категориальной переменной, выбрать сразу несколько значений, используется функция %in%.
data %>% 
  filter(`Группа крови` %in% c("A (II)", "O (I)") & `Группа` != "Группа 1")

# С количественной переменной не стоит использовать  %in%, лучше использовать between(). Эта функция помогает выбрать в переменной только те значения, которые включены в отрезок (и минимум, и максимум включены в этот отрезок).
data %>% 
  filter(between(`Возраст`, 31,34))

# Для десятичных дробей бывает очень сложно и даже не нужно фильтровать по конкретному значению. В примере выше мы отфильтровали датасет по значению эозинофилов на первом визите так, чтобы значения были примерно 3.38 ± 0.1.
data %>% 
  filter(near(`Эозинофилы_E1`, 3.38, tol = 0.1))

# фильтруем данные по условию, чтобы все переменные, содержащие в названии "Базофилы", имели значение строго больше 1.5.
data %>%
  filter(if_all(.cols = contains("Базофилы"), .fns = function(x) x > 1.5))

# теперь условие в том, чтобы хотя бы одна из этих переменных имела значение строго больше 1.5.
data %>%
  filter(if_any(.cols = contains("Базофилы"), .fns = function(x) x > 1.5))

# Фильтрация внутри каждой группы
data %>% 
  group_by(`Группа`) %>% 
  filter(`Возраст` > 30)
```

#6.5 Мутация переменных
```{r}
data %>% 
  mutate(`Женщины с червёртоё группоё крови` = ifelse(`Пол` == "Женский" & `Группа крови` == "AB (IV)", "Да", "Нет" )) %>% 
  select(`Женщины с червёртоё группоё крови`, everything ()) %>% 
  arrange(`Женщины с червёртоё группоё крови`)

data %>% 
  mutate(`Возрастная группа` = case_when(`Возраст` < 20 ~ "< 20",
                        between(`Возраст`, 20, 30) ~ "20 - 30",
                        `Возраст` > 30 ~ "> 30") %>% as.factor()) %>% 
  select(`Возраст`, `Возрастная группа`)


# Можно заметить, что тут всё не так просто. Мы меняем типы. Это нужно сделать, если переменная, в которой мы собираемся заменять значения, факторная, иначе будет возвращена ошибка. Выход — поменять тип на character, а потом обратно на factor.
data %>% 
  mutate(`Группа крови` = `Группа крови` %>% as.character() %>% replace_na("Нет данных") %>% as.factor())

# Предположим, у нас не может быть в данных третьей группы крови, и мы хотим заменить её на пропущенное значение. 
data %>% 
  mutate(`Группа крови` = `Группа крови` %>% na_if("B (III)"))

# Удаляем переменную целиком из набора данных
data %>% 
  mutate(`Группа` = NULL)

# Здесь мы применили функцию нормализации ко всем количественным переменным. 
data %>% 
  mutate(across(where(is.numeric), function(x) (x-mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)))

# А здесь только к тем, которые в названии содержат "E1"
data %>% 
  mutate(across(contains("E1"), function(x) (x-mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)))

# мы можем применять сложные функции. Например, здесь мы нормализуем только те переменные, среднее которых строго меньше 10.
data %>% 
  mutate(across(function(x) mean(x, na.rm = TRUE) < 10, function(x) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)))


# Варианты ответов
data %>% 
  mutate(across(function(x) any(near(x, 0.5, tol = 0.1)), function(x) x + 1000))

data %>% 
  mutate(across(!contains("E1") & !c(`Группа`, `Возраст`), function(x) x ^ 2))

data %>% 
  mutate(across(!contains("E1"), function(x) str_c(x, " + некая строка"))) #Работает

data %>% 
  mutate(across(!contains("E1") & !c(`Группа`, `Возраст`) & !where(is.factor), function(x) x^2), across(contains("E2"), function(x) x * 100))

# Изредка нужно итерироваться не по столбцам, а по строкам. Например, найти средние значения базофилов за оба визита. Вспомним функцию rowwise() и, наконец-то, применим её на практике.
data %>% 
  rowwise() %>% 
  mutate(`Среднее по базофилам` = mean(c_across(contains("Базофилы")))) %>% 
  ungroup() %>% 
  select(contains("Базофил"))

# Иногда нужно мутировать новые переменные по сгруппированным датафреймам. Например, мы хотим сделать переменную, в которой для каждой группы будет рассчитано значение определённой переменной за вычетом среднего по этой группе. Сделаем это.

data %>% 
  group_by(`Группа`) %>% 
  mutate(across(contains("Базофилы"), function(x) x - mean(x, na.rm = TRUE))) %>%
  ungroup() %>% 
  select(`Группа`, contains("Базофилы"))
  
```
#6.7 Переименование
```{r}

data %>% 
  rename(`Эритроциты__Визит1` = `Эритроциты_E1`, `Эритроциты__Визит2` = `Эритроциты_E2`) %>% 
  select(contains("визит"))

# dplyr::rename_with(), stringi::stri_replace_all_regex()
# Есть случаи, например, когда нам нужно заменить все коды имён на их человекочитаемые имена. Обычно для этого стоит применять связку из rename_with() и stri_replace_all_regex().
# В качестве примера переименуем все коды визитов на их названия. E1 = Визит 1, E2 = Визит 2.

library(stringi)
data %>% 
  rename_with(function(x) x %>% stri_replace_all_regex(c("_E1", "_E2"), c("_Визит1", "_Визит2"), vectorize_all = FALSE)) %>%
  glimpse()

# Ещё можно переименовывать функции только определённого типа.
data %>%
  rename_with(.cols = where(is.numeric), .fn = function(x) str_c(x, " КЛИЧЕСТВЕННАЯ ПЕРЕМЕННАЯ")) %>% 
  glimpse()

# := и !! для особых случаев переименования
# Особый случай: мы хотим написать функцию, в которую будем подавать разные переменные для того, чтобы присвоить их значения столбцам.


new_name <- "cool name"

data %>%
  rename(!! new_name := `Группа`) %>% 
  glimpse()
```

#6.8 Сортировка
```{r}
# Разумеется, сортировать можно и по нескольким переменным.
data %>% 
  arrange(desc(`Рост`), `Возраст`) #Внутри первой сортировки сортирует ещё раз

# Сортировка внутри группы
data %>% 
  group_by(`Пол`) %>% 
  arrange(`Возраст`, .by_group = TRUE)
```

#6.9 Повороты датафреймов
```{r}
# tidyr::pivot_longer()
# Длинный формат данных — это такой формат, в котором значения первого столбца повторяются и разделяют данные на "группы". Попробуем перевести наш датасет в длинный формат.

data %>% 
  select(`Группа`, contains("E1")) %>%
  pivot_longer(!`Группа`)

# Мы перевели данные в длинный формат, сохранив группировку по "Группе". Теперь у нас есть переменная имён переменных, а также переменная с их значениями. Позже нам это пригодится.

data %>% 
  select(`Группа`, contains("E1")) %>%
  mutate(ID = row_number()) %>% 
  pivot_longer(!c(`Группа`, ID)) %>%
  pivot_wider(id_cols = ID)
  
 # у нас появились дополнительные строки: мы создаём ID, чтобы функция понимала уникальность строк. 


```
#6.10 Выбор уникальных сочетаний
```{r}
# Чтобы взять подмножество уникальных значений какой-то переменной (чаще всего ID), используется функция distinct()
data %>% 
  distinct(`Группа`, .keep_all = TRUE)
# Обратите внимание, что функция берёт в каждой группе (в данном случае по переменной "Группа") только первую строку.

data %>% 
  distinct(`Группа`, pick(contains("Рост")))
```
#6.11 Разделение и склеивание
```{r}
 # Разделение переменной на две по разделителю "__"
  tibble(var_1 = rep(paste0("first part", "__", "second_part"), 10)) %>% 
  separate(var_1, into = c("var_1", "var_2"), sep = "__")

# Чтобы склеить переменную, мы можем использовать unite(). Приведём пример на основе предыдущего датафрейма.
tibble(var_1 = rep(paste0("first part", "__", "second_part"), 10)) %>% 
  separate(var_1, into = c("var_1", "var_2"), sep = "__") %>% 
  unite("new_var", var_1, var_2, sep = "_AND_")
```
#6.12 Расчёт статистик
```{r}
# Мы вычисляем среднее значение по всем количественным переменным, предварительно сгруппировав датафрейм по переменной "Группа". Как легко заметить, статистики возвращаются сразу по двум группам.
data %>% 
  select(`Группа`, where(is.numeric)) %>% 
  group_by(`Группа`) %>% 
  summarise(across(where(is.numeric), function(x) mean(x, na.rm = TRUE)))

# Подготовимся к очень серьёзному расчёту статистической таблицы.
# Чаще всего мы хотим рассчитать сразу много статистик для каждой количественной переменной, и мы можем сделать это с помощью списка из именованных функций.
statistics <- list(
      `Количество субъектов` = ~length(.x) %>% as.character(),
      `Количество (есть данные)` = ~sum(!is.na(.x)) %>%  as.character(),
      `Нет данных` = ~sum(is.na(.x)) %>%  as.character(),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))) %>%  as.character(),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2))) %>%  as.character()
)

str(data)

# Что здесь происходит? С первого взгляда кажется, что происходит некоторая каша из функций, однако на самом деле всё просто:
# 
# Знак тильды (~) и .x внутри функции — это просто краткий способ записать function(x).
# sum(!is.na(.x)) — проверка на то, что, чтобы переменная не была пустой (нельзя забывать проверить всё, что только возможно, чтобы не получить неожиданную ошибку);
# Наконец, мы округляем все значения и приводим к строковому типу, чтобы избежать ошибок при дальнейшем сведении всех результатов в красивую табличку.

# Формирование таблицы для количественных переменных
data %>% 
  select(`Группа`, where(is.numeric)) %>% 
  group_by(`Группа`) %>%
  summarise(across(where(is.numeric), statistics)) %>%
  pivot_longer(!`Группа`) %>%
  separate(name, into = c("Переменная", "Статистика"), sep = "__") %>%
  rename(`Значение` = value)

# Формирование таблицы для категориальных переменных
data %>% 
  select(`Группа`, where(is.factor)) %>%
  mutate(`Группа крови` = `Группа крови` %>% as.character() %>% replace_na("Нет данных") %>% as.factor()) %>% 
  count(`Группа`, `Группа крови`) %>% 
  group_by(`Группа`) %>%
  mutate(`Процент по группе` = (n/sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%")) %>% 
  ungroup() %>% 
  mutate(`Процент по выборке` = (n/sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%"))


rm(list=ls())
```

#Печать таблиц
```{r}
rm(list=ls())

library(flextable)

data <- read_tsv("data_tsv.tsv")

statistics <- list(
      `Количество субъектов` = ~length(.x) %>%  as.character(),
      `Количество (есть данные)` = ~sum(!is.na(.x)) %>%  as.character(),
      `Нет данных` = ~sum(is.na(.x)) %>%  as.character(),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2)))%>%  as.character(),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()) %>%  as.character(),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2))) %>%  as.character()
)

data %>% 
  select(`Группа`, where(is.numeric)) %>% 
  group_by(`Группа`) %>%
  summarise(across(where(is.numeric), statistics)) %>%
  pivot_longer(!`Группа`) %>%
  separate(name, into = c("Переменная", "Статистика"), sep = "_") %>%
  rename(`Значение` = value) %>% 
  flextable() %>% 
  theme_box() %>% 
  merge_v(c("Группа","Переменная")) %>% 
  save_as_docx(., path = "final_table.docx")


```
```{r}
library(tibble)

tibble(var_1 = c("p-value", "0.001", "test"),
       var_2 = c("p-value", "0.05", "test")) %>% 
  flextable() %>% 
  theme_box() %>% 
  merge_h(i = 3)

tibble(`Adverse events` = c("SOC Какой-то случайный длинный текст с цифраами 123456", " PT Короткий текст", "SOC Ещё какой-то длинный текст с цифрами 09876", "PT Короткий текст с цифрами 1234")) %>% 
  flextable() %>% 
  theme_box() %>% 
  align(align = "center", part = "all")


tibble(`Adverse events` = c("SOC Какой-то случайный длинный текст с цифраами 123456", " PT Короткий текст", "SOC Ещё какой-то длинный текст с цифрами 09876", "PT Короткий текст с цифрами 1234")) %>% 
  flextable() %>% 
  theme_box() %>% 
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") %>% 
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") %>% 
  bold(i = ~ str_detect(`Adverse events`, "SOC")) %>% 
  italic(i = ~ str_detect(`Adverse events`, "PT")) %>%
  width(width = 5)

is_value_sign <- function(x) {
  x %>% str_remove("<") %>% as.numeric() %>% `<`(0.05)
}

tibble("p-value" = c("<0.0001", "0.38", "0.124", "0.005", "0.05")) %>% 
         flextable() %>% 
         theme_box() %>% 
         bg(i = ~ is_value_sign(`p-value`), bg = "orange") %>% 
         save_as_docx(., path = "test_table.docx")



```

